// Generated by kea-typegen on Mon, 19 Feb 2024 18:15:11 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Color } from './colorLogic'

export interface colorLogicType extends Logic {
  actionCreators: {
    setColors: (colors: Color[][]) => {
      type: "set colors (src.logics.colorLogic)";
      payload: {
        colors: Color[][];
      };
    };
    setGreys: (greys: Color[]) => {
      type: "set greys (src.logics.colorLogic)";
      payload: {
        greys: Color[];
      };
    };
  };
  actionKeys: {
    "set colors (src.logics.colorLogic)": "setColors";
    "set greys (src.logics.colorLogic)": "setGreys";
  };
  actionTypes: {
    setColors: "set colors (src.logics.colorLogic)";
    setGreys: "set greys (src.logics.colorLogic)";
  };
  actions: {
    setColors: (colors: Color[][]) => void;
    setGreys: (greys: Color[]) => void;
  };
  asyncActions: {
    setColors: (colors: Color[][]) => Promise<any>;
    setGreys: (greys: Color[]) => Promise<any>;
  };
  defaults: {
    colors: Color[][];
    greys: Color[];
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["src", "logics", "colorLogic"];
  pathString: "src.logics.colorLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any
  ) => {
    colors: Color[][];
    greys: Color[];
  };
  reducers: {
    colors: (state: Color[][], action: any, fullState: any) => Color[][];
    greys: (state: Color[], action: any, fullState: any) => Color[];
  };
  selector: (state: any) => {
    colors: Color[][];
    greys: Color[];
  };
  selectors: {
    colors: (state: any, props?: any) => Color[][];
    greys: (state: any, props?: any) => Color[];
    tintCount: (state: any, props?: any) => number;
    cssVars: (state: any, props?: any) => string;
  };
  sharedListeners: {};
  values: {
    colors: Color[][];
    greys: Color[];
    tintCount: number;
    cssVars: string;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    tintCount: (colors: Color[][]) => number;
    cssVars: (colors: Color[][], greys: Color[]) => string;
  };
}
